<template>
  <div>
    <Breadcrumb></Breadcrumb>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
    <h1>dashboard</h1>
  </div>
</template>
<script>
import Breadcrumb from "@/components/Breadcrumb.vue";
export default {
  components: {
    Breadcrumb,
  },
};
</script>
<style></style>
